"""ATT&CK coverage: Navigator layer, Markdown report, and gap analysis vs a priority list."""
from __future__ import annotations
import json
from collections import defaultdict
from pathlib import Path
import yaml
from .loader import techniques, tactics

SEV = {"informational": 1, "low": 2, "medium": 3, "high": 4, "critical": 5}


def coverage_map(rules):
    cov = defaultdict(list)
    for r in rules:
        for t in techniques(r):
            cov[t].append(r)
    return cov


def navigator_layer(rules, name="DetectForge coverage") -> dict:
    cov = coverage_map(rules)
    return {
        "name": name, "versions": {"attack": "16", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Generated by DetectForge from the rules/ directory.",
        "gradient": {"colors": ["#c6dbef", "#08519c"], "minValue": 0, "maxValue": 3},
        "techniques": [{"techniqueID": t, "score": min(len(rs), 3),
                        "comment": "; ".join(r["title"] for r in rs)} for t, rs in sorted(cov.items())],
    }


def gaps(rules, priority_file="mappings/priority_techniques.yml"):
    have = set(coverage_map(rules))
    pri = yaml.safe_load(Path(priority_file).read_text())
    # a parent technique counts as covered if any sub-technique is covered
    def covered(tid): return tid in have or any(h.startswith(tid + ".") for h in have)
    return [p for p in pri if not covered(p["id"])], [p for p in pri if covered(p["id"])]


def markdown_report(rules, priority_file="mappings/priority_techniques.yml") -> str:
    missing, done = gaps(rules, priority_file)
    total = len(missing) + len(done)
    by_tactic = defaultdict(set)
    for r in rules:
        for ta in tactics(r):
            by_tactic[ta].update(techniques(r))
    out = ["# Detection Coverage Report", "",
           f"* Rules: **{len(rules)}**  |  Distinct techniques: **{len(coverage_map(rules))}**",
           f"* Priority-technique coverage: **{len(done)}/{total} ({100*len(done)//total}%)**", "",
           "## Coverage by tactic", "", "| Tactic | Techniques covered |", "|---|---|"]
    for ta, ts in sorted(by_tactic.items()):
        out.append(f"| {ta.replace('_', ' ').title()} | {', '.join(sorted(ts))} |")
    out += ["", "## Gaps (build next)", "", "| Technique | Name | Atomic Red Team tests |", "|---|---|---|"]
    for p in missing:
        out.append(f"| {p['id']} | {p['name']} | https://atomicredteam.io/atomic-red-team/atomics/{p['id']}/ |")
    out += ["", "## Rules", "", "| Rule | Level | Techniques |", "|---|---|---|"]
    for r in sorted(rules, key=lambda x: -SEV[x["level"]]):
        out.append(f"| {r['title']} | {r['level']} | {', '.join(techniques(r))} |")
    return "\n".join(out) + "\n"


def write_all(rules, out_dir="out"):
    Path(out_dir).mkdir(exist_ok=True)
    Path(out_dir, "attack_layer.json").write_text(json.dumps(navigator_layer(rules), indent=2))
    Path(out_dir, "COVERAGE.md").write_text(markdown_report(rules))
